
const { Review } = require('../../server/db/models')

const seedReviews = async () => {
  const reviews = await Promise.all([
    Review.create({
      clubbCourseId: 1,
      content: `<p>
      There's a kind of hum about The Beverly Country Club - a rhythm, almost.&nbsp; There's the golf staff and clubhouse staff, working together to provide an exceptional experience for the golfer from the moment they step out of the car to the moment they drive away.&nbsp; There's the caddies, joking and conversing (and maybe even napping, depending on the hour) while they await the day's loop, all lucky enough to be part of one of the best caddie programs in the nation (more Evans Scholars have come out of Beverly than any other club - anywhere).&nbsp; There's the grinders; those few guys who show up almost every day to work on their game - maybe they add a little more 'ho-hum' than 'hum'.&nbsp; There's the trees, too - century-old towers whose tops rustle, trying their best to whisper to the golfer their advice about the indecisive Chicago winds.</p>
    <p>
      Then of course, there are the sounds you wish were hums...</p>
    <p>
      Built in 1908 (the same year the Ford Motor Company came out with the Model T, maybe you've heard of it), The Beverly Country Club bore witness to Chicago's coming-of-age.&nbsp; Once an intersection that perhaps saw only a few of those Model T's per day, 87th and Western Avenue is now a bustling collision of thoroughfares that provides constant and ample noise for Beverly's golfers. &nbsp;Combine that with the freight train line that runs down the entirety of the west-side property line and the landing pattern for Midway airport that lies directly overhead, and you've got planes, trains, and automobiles (without the comedic relief of Steve Martin and John Candy, unfortunately).</p>
    <p>
      The Course:</p>
    <p>
      Donald Ross's design at The Beverly Country Club compels you to think about what the land on the south side of Chicago looked like before the city enveloped it.&nbsp; This quarter of a square mile of rolling terrain has remained untouched by would-be builders of homes, offices, and storefronts who would have gladly erased the storied hills and valleys.&nbsp; The preeminent feature of the front nine is a ridge that runs east to west, providing dramatic elevation changes that come in to play on several of the holes. &nbsp;This ridge was the southern shore of prehistoric Lake Chicago, a body of water that drained after the retreat of the Wisconsin Glacier during the last glacial period.&nbsp; Perched atop this ridge is the championship tee box on the second hole, which is actually the highest point of elevation in the city of Chicago.&nbsp; I guess after the first hole you could say that your round is - quite literally - 'all downhill from here'.</p>
    <p>
      One of the more unique aspects of The Beverly Country Club is that the two nines are on opposite sides of 87th street, connected via a one-lane tunnel (also known as a traffic jam if you forget to hit the signal button that warns the other side of your imminent arrival).&nbsp; The golf shop, caddie shack and front nine sit on the north side of 87th, with the clubhouse, pool, practice facilities and back nine to the south of 87th.&nbsp; While the elevation change on the front nine is severe and obvious, the south side of the golf course challenges you with its subtlety.&nbsp; The 13th hole is an excellent example of that subtlety, and Jason's favorite hole on the course.&nbsp; A relatively short par 4 with a blind tee shot, the approach on 13 doesn't feel like it requires the extra club that it most certainly does.&nbsp;&nbsp;&nbsp;</p>
    <p>
      The bunkering at Beverly was one of the most integral portions of Ron Pritchard's 2003 course renovation, and has since sparked some mixed reactions.&nbsp; Nearly every bunker on the property was deepened, and the bunker faces were made steeper and more penal. &nbsp;Additionally, the faces of the bunkers were seeded with a wiry fescue grass that is allowed to grow to about 6 inches, making advancement of the golf ball nearly impossible in some cases.&nbsp; The severity, depth, and placement of the bunkers have been a point of controversy since the renovation.&nbsp; In our opinion, the severity and depth are appropriate for a championship caliber golf course, but the placement of the bunkers could have been given a little more thought.&nbsp; On a number of holes, the bunkers punish the wrong players.&nbsp; Better, longer-hitting players can carry nearly all of the bunkers on the course with driver off the tee.&nbsp; It is even to the point that if a good player is hitting driver exceptionally well, Beverly can be left nearly defenseless (7,016 completely tipped out really isn't much of a match for a long hitter).&nbsp; On the other hand, the shorter hitter will find the bunkers quite a bit more often, as they sit generally 230-250 yards from the tee.&nbsp; Numbers 5, 8, 11, 14, and 16 are perfect examples of holes with poorly placed bunkers, with the most severe bunkers on 11 and 16 (faces so steep you literally cannot advance the ball more than 20 yards if your ball comes to rest in the fescue on the face).&nbsp; Some of the better players at Beverly have never visited these pits, and some of the higher handicaps probably wake up in the middle of the night in a cold sweat following a nightmare about them.&nbsp;</p>
    <p>
      Like most Ross courses, the greens are easily the most interesting feature. Most of Beverly's greens slant from back to front with only a few exceptions.&nbsp; A front hole location on 5 and almost any hole location on 17 warmly invite you to putt your ball clear off the front of the green when the greens are rolling nicely.&nbsp; 5's green holds a special punishment for a downhill putt hit with too much zeal - take a ride down the ridge and enjoy a 20-yard pitch back up the 25-foot slope.&nbsp;</p>
    <p>
      The majority of the severe greens on the course are located on the back nine, which, in our opinion, is the more interesting nine at Beverly (whether it is the more difficult of the two nines is debatable).&nbsp; The severe slopes on Beverly's greens catch your eye, but the subtle ones will catch your ball.&nbsp; This is the true challenge at Beverly - rolling the ball.&nbsp; The golfer has to take in to account an incredible amount of nuance and realize that on some holes, putts roll in directions that the eye can't see and the mind can't comprehend.&nbsp; The greens might not always look difficult, but when you tally up your putts on a good ball striking day you’ll realize why it can be so tough to score well at Beverly.&nbsp; Even when the greens are rolling true, putts seem to burn the edge of the cup more often than not.</p>
    <p>
      Members and guests alike will agree that this golf course gives you the opportunity to practice a couple different things ad nauseum: playing with noise, hitting punch shots out of thick rough, and putting straight down a hill that quite literally fills you with fear.&nbsp;</p>
    <p>
      The Club:</p>
    <p>
      The clubhouse, pool, and practice facilities occupy the south side of the club and provide a nice setting for a relaxing day or a pleasant meal with family or friends.&nbsp; While none of the facilities are necessarily world-class, they are more than adequate for a high-quality neighborhood country club.&nbsp; On the other hand, the staff at the club makes a great deal of difference.&nbsp; From the bag drop and valet to the men's locker room to the golf shop to the bar - Beverly has attentive and respectful people who endeavor to make your experience second-to-none.&nbsp;</p>
    <p>
      The recently renovated practice facilities at Beverly now offer a short game area that allows players to practice just about any shot inside 100 yards. The area consists of 3 greens - one of which is surrounded by 3 bunkers - and a lot of fairway with a minimal yet serviceable amount of rough. The driving range at Beverly is quite nice, with about 2500 square yards of neatly trimmed fairway for practice, but will be improved still when the plans to make the range double sided come to fruition at the end of the year.</p>
    <p>
      History:</p>
    <p>
      Conditioning at Beverly in recent years has been a bit of a struggle.&nbsp; Though the conditions have never been truly awful, they have been less than 'high-end country club level' in recent years. A recent push to get back to the great conditioning that Beverly was once known for has resulted in some noticeable changes in 2011.&nbsp; The tree removal program that went into effect during Pritchard's renovation was an attempt to allow the rough to get more sunlight and grow thicker, providing a tougher test for the golfer.&nbsp; The plan has finally seemed to take, as the rough has been as thick as ever at Beverly this year, and at times makes a leisurely afternoon round feel like the weekend at the US Open.&nbsp; The long, thick rough makes Beverly feel more like the championship golf course that its rich history suggests.&nbsp;</p>
    <p>
      Since opening in 1908, Beverly has played host to many great championships, including the Western Open (1910, 1963, 1967, 1970), the 1930 Western Amateur, the 1931 US Amateur, and the 2009 US Senior Amateur.&nbsp; These championships have yielded great victors, including Chick Evans, Francis Ouimet, Arnold Palmer, Jack Nicklaus, and Luke Donald.&nbsp; The prestige of The Beverly Country Club continues to grow as the club has received the distinction of hosting the 2011 Western Junior Amateur Championship and the 2014 Western Amateur Championship.</p>
    <p>
      With a history like that, there’s no denying that the golf course has held its own over time.&nbsp; It may not be the most awe-inspiring golf course in the Chicagoland area, but it keeps things interesting enough that golfers always seem delighted when they walk off the 18th green.&nbsp; After winning the 2009 US Senior Amateur, Marvin “Vinny” Giles, one of golf's most decorated and respected amateur players, summed up Beverly in a similar fashion to many other greats before him, saying: “This golf course is fun.&nbsp; This golf course passes the test that I think is the ultimate test in golf, a golf course you can play every day and never get tired of.&nbsp; I think that is the ultimate test of a golf course.”</p>
    <p>
      We'll 2nd that, Vinny.</p>`,
      status: 'published',
      title: 'Tranquility Amid Turmoil',
      datePosted: '2018-03-03',
      imgUrl: 'http://www.2playthetips.com/images/Beverly.jpg'
    }),
    Review.create({
      clubbCourseId: 2,
      content: `<p>
      You all know Bruce Wayne, right?&nbsp; The handsome, thrill-seeking, Lamborghini-driving billionaire playboy with a crime-fighting alter ego?&nbsp; Whether he's impressing the women of Gotham City's high society or combating the criminals of its dregs, he's got to be confident in his abilities.&nbsp; Maybe his ego gets the better of him from time to time, but you've got to admit it: he's got quite a lot going for him.&nbsp;</p>
    <p>
      Now we all know that Bruce's parents were taken from him at a young age, so someone had to step in.&nbsp; Someone who could handle Bruce's personality.&nbsp; Someone who was willing to speak up; to put Bruce in his place when no one else is willing or able.&nbsp; Someone who awards a job well done with a pat on the back, not a ritzy party and copious congratulations.&nbsp; Someone who doesn't stand for mediocrity.&nbsp; Someone who expects and rewards the best, because the best is all that's known in the Wayne family.</p>
    <p>
      This someone is none other than the Wayne family butler, Alfred Pennyworth.&nbsp; A loyal man.&nbsp; A traditional man.&nbsp; A voice of wisdom.&nbsp; A gentleman's gentleman.&nbsp;</p>
    <p>
      Since its inception, another Butler - Butler National Golf Club - has followed the same set of rules and beliefs that Alfred used with his billionaire Batman.&nbsp; Keep 'em humble, keep 'em honest, teach 'em their limitations, and make sure they stay true to what they believe in, because without those beliefs they just wouldn't be the same.&nbsp; And every once in a while make 'em smile when they realize they've got the best butler around.&nbsp;</p>
    <p>
      Butler tends to some of Chicago's finest with service that rivals a 5-star resort.&nbsp; Upon entering, we were met with such service.&nbsp; After warming up on the driving range (which were once the polo grounds), we headed inside for lunch.&nbsp; We left the lunch table quite satisfied; now convinced that this particular club has more going for it than just the golf course.</p>
    <p>
      Finally it was time to hit the course.&nbsp; As we walked past the putting area toward the first tee, we both felt that Butler seemed to have that something special we keep an eye out for when playing great courses.&nbsp; Now it was time to go find out for sure.&nbsp; Stepping up to our first shots, we noticed a storm front in the distance promising the rain that would prove to predominate our day.&nbsp; Off and on over the next four hours Mother Nature and Butler National joined forces, laying siege to our pride and our scores.&nbsp; Wet conditions on a course this tough can make you feel like calling out for your mommy.&nbsp; Sorry kid, she won't be coming to save you.&nbsp; Not at Butler.</p>
    <p>
      Butler was without a doubt one of the most difficult courses we've played.&nbsp; To its credit, though, it's interesting, it's more fair than not, and it's aesthetically pleasing all at the same time. &nbsp;In all honesty, Butler could host the world's best and easily keep them at bay for four rounds.&nbsp; With the rough being a uniform 6 inches (and wet), we learned quickly that putting the ball in the fairway would be key to scoring well.&nbsp; More than anything, Butler is a ball strikers golf course.&nbsp; George Fazio put a premium on hitting the fairway here; almost every green on the course sits on a slightly awkward angle, demanding either an accurate tee shot for an easier approach, or an exacting approach from a less-than-ideal spot in the fairway or rough.&nbsp; Take the par 4 tenth hole, for example.&nbsp; This hole doglegs very slightly to the left, with water hugging the left side of the fairway.&nbsp; The green here is angled away from the golfer and to the right, with a creek short of the green.&nbsp; The closer your tee ball hugs the water, the better the shot you have to the angled green, particularly if there is a back pin.&nbsp; The right side fairway bunker on this hole will gobble up a lengthy wayward drive, demanding your run-of-the-mill 175 yard bunker shot over a creek to a shallow, elevated green.&nbsp; I know we all have that shot in our bags.&nbsp;</p>
    <p>
      Another excellent example is the par 4 fourth.&nbsp; This dogleg right runs uphill, but you can't see the green from the tee.&nbsp; If you happen to flare one out right here, you're in trouble.&nbsp; This green is well bunkered and angles away from the golfer to the right.&nbsp; An approach from the left side of the fairway is tough (long and uphill), but offers the only angle that allows a run-up of any kind.&nbsp; Granted, it's only about 5 yards wide, but it's still better than having to hoist it over a deep greenside bunker and land it on a piece of green that runs away from you due to the back side of the bunker.&nbsp; If you're firing this shot from the fairway, you can most likely rely on spin to hold the shot in place.&nbsp; If you're coming from the rough, you might as well take out your sand wedge, as another bunker guards the back side of the green.&nbsp;</p>
    <p>
      The other key to scoring well at Butler National is playing the par 3s well - or at least not exploding on them.&nbsp; This is definitely the highlight of George Fazio's layout.&nbsp; The par 3s here are the best grouping of one-shotters either of us could remember playing.&nbsp; Holes 5, 8 11, 13 demand well struck mid- to long-irons - maybe even a hybrid or two depending on the wind - and are masterfully guarded by water hazards that wait calmly, eager to devour any misstruck tee shots.&nbsp;</p>
    <p>
      Two of these par 3s, 5 and 13, provide the shoreline for a third of the most prominent water hazard on property. The other third is made up of the par 4 14th, a wonderful par 4 that moves from right to left around the edge of the lake.&nbsp; All three of these holes provide excellent views of one another, and would provide for an amazing scene for spectators at a tournament.&nbsp; The routing of these holes around the pond makes for a kind of 360 degree amphitheater, adding to the overall aesthetics and providing much of the OMG Factor at Butler National.&nbsp;</p>
    <p>
      The routing at Butler is definitely worth touching on.&nbsp; There are many holes that utilize the creek that runs through the property, and as stated before, the holes around the lake are spectacular.&nbsp; We are always fans of courses that return to the clubhouse between nines, as well as finishing holes that offer an impressive view of the clubhouse.&nbsp; The routing of two of the par 5s, 7 and 15, is also very fun and interesting.&nbsp; These severe dogleg rights are tough, but overwhelm the golfer with a feeling of awe and curiosity that outweigh the feelings of dread and low self-esteem that usually pervade the thoughts of those who play them.&nbsp;</p>
    <p>
      The only thing that we didn't like out here was the ninth hole.&nbsp; This long, demanding par 4 is probably the toughest hole on the course.&nbsp; Without question the most tree-lined hole on the property, the landing area for the ninth narrows as it nears the green.&nbsp; The green is also elevated and guarded well by a left greenside bunker.&nbsp; Additionally, there is a hazard to the left of the green.&nbsp; This is the only hole on the course that quite literally demands that you place your tee shot.&nbsp; A drive that winds up on the right side of this fairway has a decent chance of having no shot to the green - unless you're comfortable with a 15 yard cut with an 8 iron.&nbsp; This green angles away and to the left, calling for a draw.&nbsp; However, the only way to be able to hit a draw to the green is if you are on the far left side of the fairway.&nbsp; Any other place, and your approach will most likely get caught up in the right side trees.&nbsp; This hole is tough enough, and the angles call for a more open approach to the green.&nbsp; If a few of those trees came out on the right side, we think the design would benefit quite a bit.&nbsp;&nbsp;</p>
    <p>
      Paul Butler had a great vision for the piece of land on which Butler National now lies; a piece of land that was not the best naturally occurring golf course land in the world.&nbsp; He wanted a championship golf course brawny enough that even the worlds best wouldn't dare dream of going low.&nbsp; Since his idea has become a reality through George Fazio's creation, Butler National has done its best to live up to Paul's idea of what a great golf course should be.&nbsp; Butler National has done so, and in doing so one can say that it has even taken on a certain personality.&nbsp; It lives and breathes (I daresay more calmly than the men that attempt to tackle it), protecting the vision that Paul Butler had.&nbsp; Why does it give a damn, you ask?&nbsp; Butler National gives a damn because a good man once had a vision for a championship golf course; one that would keep everyone humble and keep the integrity of this great game intact.&nbsp; One that expects the best; rewards the best.&nbsp; Butler National will always do that.&nbsp; It's Paul Butler's gentleman.&nbsp;</p>
    <p>
      Nay... It's golf's gentleman.</p>`,
      status: 'published',
      title: 'Everyone Could Use A Good Butler',
      datePosted: '2018-03-07',
      imgUrl: 'http://www.2playthetips.com/images/Butler.jpg'
    }),
  ])

  console.log(`seeded ${reviews.length} reviews`)
}

module.exports = seedReviews